dist: trusty
sudo: required
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
os:
- linux
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- echo "$TRAVIS_BRANCH"
- echo "$TRAVIS_PULL_REQUEST"
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then openssl aes-256-cbc -K $encrypted_100b62b33cf9_key -iv $encrypted_100b62b33cf9_iv -in travis_rsa.enc -out travis_rsa -d; fi
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export CHROME_BIN=chromium-browser
script:
- yarn run lint
- yarn run test
- npm run-script coveralls
- yarn run integration
- yarn run build:demo
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then node_modules/.bin/gh-pages-travis; fi

env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="dist"
    - TARGET_BRANCH="gh-pages"
    - SSH_KEY="travis_rsa"
    - GIT_NAME="travis"
    - GIT_EMAIL="andzej.maciusovic@gmail.com"
